insert into position (positionid, positionname) values (1, 'Subcontractor');
insert into position (positionid, positionname) values (2, 'Supervisor');
insert into position (positionid, positionname) values (3, 'Surveyor');
insert into position (positionid, positionname) values (4, 'Construction Expeditor');
insert into position (positionid, positionname) values (5, 'Construction Manager');
insert into position (positionid, positionname) values (6, 'Surveyor');
insert into position (positionid, positionname) values (7, 'Construction Manager');
insert into position (positionid, positionname) values (8, 'Engineer');
insert into position (positionid, positionname) values (9, 'Estimator');
insert into position (positionid, positionname) values (10, 'Engineer');
